### ISSUE TITLE
Clicking "run OK tests" button doesn't save the notebook

### ISSUE THREAD

**Issue by henryem** [dsten/notebook-ok-extension#14]
...and therefore tests are often run on a stale version of submission.py.  This is very confusing to students when it happens, and it happens a lot.

I don't know if this is trivial to reproduce or if it requires nontrivial steps.  Perhaps it happens if tests are run multiple times.

**Comment by papajohn** [comment]
The way in which `ok` interacts with the notebook is changing, so this issue is obsolete. Good point, though.
