### ISSUE TITLE
Scrolls to bottom of notebook when Scratch is activated

### ISSUE THREAD

**Issue by papajohn** [dsten/notebook-ok-extension#5]
When I press "Scratch", my notebook scrolls to the bottom of the page. I think maybe this behavior is new, meaning that I broke something... any suggestions? Only happens the first time I click "Scratch"

![a1](https://cloud.githubusercontent.com/assets/320145/9413846/6b377368-47e9-11e5-93c4-622401abce2a.gif)

**Comment by alvinwan** [comment]
I can try to fix it. It actually has to do with how I implemented it: the first time you click, it inserts a cell at the bottom. After that, it just uses the new cell.

Jupyter API should have a way of inserting a cell, without simulating a click.
